
[general]
import = [
  "~/.cache/wal/colors-alacritty.toml",
]

[font.normal]
family = "GoMono Nerd Font mono"
style = "Bold"

[font]
size = 12.0

[window]

opacity = 0.95

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"
